// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4bDmOAjHR52WkXaahLS6_V3GExAjXy1U',
    appId: '1:218160422207:web:895e5063c02eca22b7c78a',
    messagingSenderId: '218160422207',
    projectId: 'first-ever-app-ayga',
    authDomain: 'first-ever-app-ayga.firebaseapp.com',
    storageBucket: 'first-ever-app-ayga.appspot.com',
    measurementId: 'G-PXTRG2CZHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOVzJrH8bxPkkMkw89KdGN2d2pxXbf_v4',
    appId: '1:218160422207:android:fc16e748e117cb9cb7c78a',
    messagingSenderId: '218160422207',
    projectId: 'first-ever-app-ayga',
    storageBucket: 'first-ever-app-ayga.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAew5xD7oNmAoiylFc3tpH_DDgo7CT-axQ',
    appId: '1:218160422207:ios:94ea52c339ec8fa8b7c78a',
    messagingSenderId: '218160422207',
    projectId: 'first-ever-app-ayga',
    storageBucket: 'first-ever-app-ayga.appspot.com',
    iosClientId: '218160422207-vk45vg5cbsnumt4d5lljdnf1jqpr0g23.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAew5xD7oNmAoiylFc3tpH_DDgo7CT-axQ',
    appId: '1:218160422207:ios:94ea52c339ec8fa8b7c78a',
    messagingSenderId: '218160422207',
    projectId: 'first-ever-app-ayga',
    storageBucket: 'first-ever-app-ayga.appspot.com',
    iosClientId: '218160422207-vk45vg5cbsnumt4d5lljdnf1jqpr0g23.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
